# properties to yaml
# https://mageddo.com/tools/yaml-converter
server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://ec2-13-125-96-73.ap-northeast-2.compute.amazonaws.com:3306/dotime?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: '1234'
  security:
    user:
      name: user
      password: '1234'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show-sql: 'true'

    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql   # 추가 해준 부분
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분

springdoc:
  api-docs:
    path: /api-docs

jwt:
  header: Authorization
  secret: rutyweorituwyerotiuweyrtoiuweyrtoweiurtywoeighdfsojkghsdfgsdofiguwyertouwasdasdasdasdasdqwegfhdghnbckj

  access:
    expiration: 80
    header: Authorization

  refresh:
    expiration: 90
    header: Authorization-refresh
  access-token-validity-in-seconds: 6000 # 10 min

#    oauth2:
#      client:
#        registration:
#          github:
#            clientId: github-client-id
#            clientSecret: github-client-secret
#          google:
#            client-id: google-client-id
#            client-secret: google-client-secret